site_name: Metagenome tutorial

pages:
- Home: 'index.md'
- Jupyter: 'startup.md'
- QC: 'qc.md'
- Assembly: 'assembly.md'
- Binning: 'binning.md'
- Visualization: 'anvio.md'
- HiC: 'hic.md'
- Everything Else: 'everythingelse.md'

