site_name: Metagenome tutorial

pages:
- [index.md, Home]
- [startup.md, Jupyter startup]
- [qc.md, FastQC]
- [assembly.md, Metagenome assembly]
- [binning.md, Genome binning]
- [hic.md, Metagenome HiC]

